public class Buff
{
    public string Id{get; set;}
    public string Level{get; set;}
    public string Name{get; set;}
    public string Desc{get; set;}
    public string EffectID{get; set;}
    public string ShaderID{get; set;}
    public string MaterialId{get; set;}
    public string Intensity{get; set;}
    public string IsStackable{get; set;}
    public string IsCountable{get; set;}
    public string MaxStackNum{get; set;}
    public string IsMaxStackOnCreate{get; set;}
    public string MaxStackNewBuffID{get; set;}
    public string RemoveOnCast{get; set;}
    public string ActiveBegionAttribOnCast{get; set;}
    public string Count{get; set;}
    public string Interval{get; set;}
    public string DotType{get; set;}
    public string TriggerHP{get; set;}
    public string Exclude{get; set;}
    public string SrcExclude{get; set;}
    public string FunctionExclude{get; set;}
    public string DescType{get; set;}
    public string DescMSec{get; set;}
    public string DescEffect{get; set;}
    public string DescMinTick{get; set;}
    public string DescMaxCount{get; set;}
    public string IsSave{get; set;}
    public string DeleteOnDeath{get; set;}
    public string DeleteOnSafe{get; set;}
    public string DeleteOnBattleEnd{get; set;}
    public string DeleteOnLeaveScene{get; set;}
    public string DeleteOnNoFighting{get; set;}
    public string DeleteOnSpecialState{get; set;}
    public string DeleteOnSpecialRun{get; set;}
    public string IsOffLineClock{get; set;}
    public string FindTargetsRelasion{get; set;}
    public string FindTargetsCountMax{get; set;}
    public string FindTargetsRadius{get; set;}
    public string FindTargetsCharacterType{get; set;}
    public string DispelType{get; set;}
    public string NeedAttrPointPercent{get; set;}
    public string NeedAttrPointID{get; set;}

    public string BeginAttrib1{get; set;}
    public string BeginValue1A{get; set;}
    public string BeginValue1B{get; set;}
    public string BeginAttrib2{get; set;}
    public string BeginValue2A{get; set;}
    public string BeginValue2B{get; set;}
    public string BeginAttrib3{get; set;}
    public string BeginValue3A{get; set;}
    public string BeginValue3B{get; set;}
    public string BeginAttrib4{get; set;}
    public string BeginValue4A{get; set;}
    public string BeginValue4B{get; set;}
    public string BeginAttrib5{get; set;}
    public string BeginValue5A{get; set;}
    public string BeginValue5B{get; set;}
    public string BeginAttrib6{get; set;}
    public string BeginValue6A{get; set;}
    public string BeginValue6B{get; set;}

    public string ActiveAttrib1{get; set;}
    public string ActiveValue1A{get; set;}
    public string ActiveValue1B{get; set;}
    public string ActiveAttrib2{get; set;}
    public string ActiveValue2A{get; set;}
    public string ActiveValue2B{get; set;}
    public string ActiveAttrib3{get; set;}
    public string ActiveValue3A{get; set;}
    public string ActiveValue3B{get; set;}

    public string EndTimeAttrib1{get; set;}
    public string EndTimeValue1A{get; set;}
    public string EndTimeValue1B{get; set;}
    public string EndTimeAttrib2{get; set;}
    public string EndTimeValue2A{get; set;}
    public string EndTimeValue2B{get; set;}
    public string EndTimeAttrib3{get; set;}
    public string EndTimeValue3A{get; set;}
    public string EndTimeValue3B{get; set;}

    public string BeClearAttrib1{get; set;}
    public string BeClearValue1A{get; set;}
    public string BeClearValue1B{get; set;}
    public string BeClearAttrib2{get; set;}
    public string BeClearValue2A{get; set;}
    public string BeClearValue2B{get; set;}
    public string BeClearAttrib3{get; set;}
    public string BeClearValue3A{get; set;}
    public string BeClearValue3B{get; set;}

    public string BeDispelAttrib1{get; set;}
    public string BeDispelValue1A{get; set;}
    public string BeDispelValue1B{get; set;}

    public string BeShieldAttrib1{get; set;}
    public string BeShieldValue1A{get; set;}
    public string BeShieldValue1B{get; set;}

    public string BeDelAttrib1{get; set;}
    public string BeDelValue1A{get; set;}
    public string BeDelValue1B{get; set;}
    public string IconAtlas{get; set;}
    public string IconName{get; set;}
    public string ShowDesc{get; set;}
    public string ShowType{get; set;}
    public string ShowValue{get; set;}
    public string SyncToSelfClient{get; set;}
    public string SyncToOtherClient{get; set;}
    public string SrcVisible{get; set;}
}